version: 2

jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Package.resolved" }}
      - run: swift build
      - save_cache:
          key: dependency-cache-{{ checksum "Package.resolved" }}
          paths:
            - .build
      - run: swift test

workflows:
  version: 2
  default:
    jobs:
      - build-and-test
